plugins {
    alias(libs.plugins.android.application)
    alias(libs.plugins.kotlin.android)
    alias(libs.plugins.ksp)
    alias(libs.plugins.dagger.hilt)
    id("kotlin-kapt")
}

android {
    namespace 'com.matheus.picpay'
    compileSdk 35

    defaultConfig {
        applicationId "com.matheus.picpay"
        minSdk 21
        targetSdk 34
        versionCode 1
        versionName "1.0"

        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"
    }

    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }
    kotlinOptions {
        jvmTarget = '1.8'
    }
    buildFeatures {
        viewBinding = true
    }

}

dependencies {

    implementation(libs.guava) // Implementando via Version Catalog


    //LifeCycle
    implementation (libs.androidx.lifecycle.runtime)
    implementation (libs.androidx.lifecycle.viewmodel)
    implementation (libs.androidx.lifecycle.livedata)

    //Retrofit
    implementation(libs.retrofit)
    implementation(libs.converter.gson)

    // OkHttp
    implementation(platform(libs.okhttp.bom))
    implementation(libs.logging.interceptor)

    //Dagger hilt
    implementation(libs.dagger.hilt)
    implementation (libs.testng)
    implementation (libs.androidx.junit.ktx)
    implementation (libs.core)
    implementation libs.androidx.benchmark.common
    ksp(libs.hilt.compiler)



    // Google Maps
    implementation (libs.play.services.maps)

    //Testes unitary
    testImplementation (libs.junit)

    // Testes instrumentals
    androidTestImplementation (libs.androidx.junit)
    androidTestImplementation (libs.androidx.espresso.core)

    // Testes
    testImplementation(libs.mockito.core)
    testImplementation(libs.mockito.inline)
    testImplementation(libs.coroutines.test)
    testImplementation(libs.androidx.test.core)
    testImplementation(libs.androidx.test.ext.junit)
    testImplementation(libs.androidx.arch.core.testing)

    androidTestImplementation(libs.androidx.test.runner)
    androidTestImplementation(libs.androidx.test.rules)
    androidTestImplementation(libs.coroutines.test)
    testImplementation (libs.mockito.kotlin)


    // Testes instrumentados (MockWebServer)
    androidTestImplementation (libs.okhttp.okhttp)
    androidTestImplementation(libs.okhttp.mockwebserver)

    //Core
    implementation (libs.androidx.core.ktx)
    implementation (libs.androidx.appcompat)
    implementation (libs.recyclerview)
    implementation(libs.maps.utils)

    // Material Design
    implementation (libs.material)


    implementation (libs.androidx.activity)
    implementation (libs.androidx.constraintlayout)

    // Room Database
    implementation (libs.room.runtime)
    implementation (libs.room.ktx)

    // Testes para Room
    testImplementation (libs.room.testing)

    implementation(libs.facebook.shimmer)
    implementation(libs.fragmentKtx)
}